name: Action Name

on:
  pull_request:
    branches: [my_branch]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  my_job_name: # You can replace 'my_job_name' with a suitable name for your job.
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo tests
      run: echo "tests"
      