name: Action Name

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize

jobs:
  my_job_name: # You can replace 'my_job_name' with a suitable name for your job.
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo tests
      run: echo "tests"
