name: My Workflow

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  my_job:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: My Step
      run: echo "Running my steps..."
